name: 'Upload Code to EsoUI'
description: 'Upload Code to EsoUI'
inputs:
  path:
    description: 'Path of the files (folder name)'
    required: true
    default: './'
  readme:
    description: 'Path of the readme file (not including folder path)'
    required: false
    default: 'README.md'
  changelog:
    description: 'Path of the changelog file (not including folder path)'
    required: false
    default: 'changelog.txt'
  EsoUIToken:
    description: 'Token from EsoUI'
    required: true
  EsoUIID:
    description: 'ID from EsoUI'
    required: true
  version:
    description: 'Version of the addon'
    required: true
  artifact:
    description: 'Build Artifact to upload'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
